# Generated by Django 6.1.1 on 2026-09-07 00:30

import django.db.models.deletion
import trusts.zero.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trusts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('description', models.TextField(blank=True)),
                ('trust', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_content', to='trusts.trust')),
            ],
            options={
                'ordering': ('title',),
                'default_permissions': ('add', 'read', 'change', 'delete'),
            },
            bases=(trusts.zero.models.ReadonlyFieldsMixin, models.Model),
        ),
    ]
